object Versions {
    const val EXPOSED_VERSION = "0.44.1"
    const val KOTLIN_LOGGING_VERSION = "3.0.5"
    const val MOCKK_VERSION = "1.13.8"
    const val KOTEST_VERSION = "5.7.2"
    const val KOTEST_ARROW = "1.4.0"
    const val KOTEST_TEST_CONTAINERS = "2.0.2"
    const val JUNIT_VERSION = "5.10.0"
    const val ARROW_VERSION = "1.2.1"
    const val JACKSON_VERSION = "2.15.3"
    const val KOTLIN_COROUTINES_VERSION = "1.7.3"
    const val AWAITILITY_VERSION = "4.2.0"
    const val JAVALIN_VERSION = "5.6.3"
    const val HIKARI_CP_VERSION = "5.0.1"
    const val POSTGRESQL_VERSION = "42.6.0"
    const val TEST_CONTAINERS_VERSION = "1.19.1"
    const val QUARTZ_VERSION = "2.3.2"
}